RestClients:
  test-rest:
    Url: http://localhost/test
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    Properties:
      JSON.Deserialization.FAIL_ON_UNKNOWN_PROPERTIES: 'false'
