package ch.ivyteam.testservice.country.client;

import jakarta.annotation.Generated;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.2.2
 * 2026-08-13T13:20:51.198+02:00
 * Generated source version: 4.2.2
 *
 */
@WebService(targetNamespace = "http://country.testservice.ivyteam.ch/", name = "CountryService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-08-13T13:20:51.198+02:00", comments = "Apache CXF 4.2.2")
public interface CountryService {

    @WebMethod
    @WebResult(name = "getCountryByShortNameResponse", targetNamespace = "http://country.testservice.ivyteam.ch/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-08-13T13:20:51.198+02:00")
    public GetCountryByShortNameResponse getCountryByShortName(

        @WebParam(partName = "parameters", name = "getCountryByShortName", targetNamespace = "http://country.testservice.ivyteam.ch/")
        GetCountryByShortName parameters
    );

    @WebMethod
    @WebResult(name = "longRunningOperationResponse", targetNamespace = "http://country.testservice.ivyteam.ch/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-08-13T13:20:51.198+02:00")
    public LongRunningOperationResponse longRunningOperation(

        @WebParam(partName = "parameters", name = "longRunningOperation", targetNamespace = "http://country.testservice.ivyteam.ch/")
        LongRunningOperation parameters
    );

    @WebMethod
    @WebResult(name = "returnSoapFaultResponse", targetNamespace = "http://country.testservice.ivyteam.ch/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-08-13T13:20:51.198+02:00")
    public ReturnSoapFaultResponse returnSoapFault(

        @WebParam(partName = "parameters", name = "returnSoapFault", targetNamespace = "http://country.testservice.ivyteam.ch/")
        ReturnSoapFault parameters
    );
}
