package ch.ivyteam.testservice.country.client;

import java.net.URL;
import jakarta.annotation.Generated;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.2.2
 * 2026-08-13T13:20:51.250+02:00
 * Generated source version: 4.2.2
 *
 */
@WebServiceClient(name = "CountryServiceService",
                  wsdlLocation = "CountryServiceService.wsdl",
                  targetNamespace = "http://country.testservice.ivyteam.ch/")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-08-13T13:20:51.250+02:00", comments = "Apache CXF 4.2.2")
public class CountryServiceService extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-08-13T13:20:51.250+02:00")
    public static final URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-08-13T13:20:51.250+02:00")
    public static final QName SERVICE = new QName("http://country.testservice.ivyteam.ch/", "CountryServiceService");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-08-13T13:20:51.250+02:00")
    public static final QName CountryServicePort = new QName("http://country.testservice.ivyteam.ch/", "CountryServicePort");
    static {
        URL url = CountryServiceService.class.getResource("CountryServiceService.wsdl");
        if (url == null) {
            url = CountryServiceService.class.getClassLoader().getResource("CountryServiceService.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(CountryServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "CountryServiceService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-08-13T13:20:51.250+02:00")
    public CountryServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-08-13T13:20:51.250+02:00")
    public CountryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-08-13T13:20:51.250+02:00")
    public CountryServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-08-13T13:20:51.250+02:00")
    public CountryServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-08-13T13:20:51.250+02:00")
    public CountryServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-08-13T13:20:51.250+02:00")
    public CountryServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CountryService
     */
    @WebEndpoint(name = "CountryServicePort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-08-13T13:20:51.250+02:00")
    public CountryService getCountryServicePort() {
        return super.getPort(CountryServicePort, CountryService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountryService
     */
    @WebEndpoint(name = "CountryServicePort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-08-13T13:20:51.250+02:00")
    public CountryService getCountryServicePort(WebServiceFeature... features) {
        return super.getPort(CountryServicePort, CountryService.class, features);
    }

}
