<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>ch.ivyteam.enginecockpit</groupId>
    <artifactId>engine-cockpit-config</artifactId>
    <version>14.0.0-pf15-SNAPSHOT</version>
    <relativePath>../maven-config</relativePath>
  </parent>

  <groupId>ch.ivyteam.enginecockpit</groupId>
  <artifactId>engine-cockpit-test</artifactId>
  <version>14.0.0-pf15-SNAPSHOT</version>
  <packaging>iar</packaging>

  <properties>
    <skip.tests>true</skip.tests>
  </properties>

  <dependencies>
    <dependency>
      <groupId>ch.ivyteam.enginecockpit</groupId>
      <artifactId>engine-cockpit</artifactId>
      <version>${project.version}</version>
      <type>iar</type>
    </dependency>
    <dependency>
      <groupId>com.axonivy.ivy.api.test</groupId>
      <artifactId>ivy-test-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.axonivy.ivy.api</groupId>
      <artifactId>ivy-poi-api</artifactId>
      <scope>test</scope>
    </dependency>
     <dependency> <!-- TODO: remove after core merge -->
      <groupId>org.primefaces</groupId>
      <artifactId>primefaces</artifactId>
      <version>15.0.17</version>
      <classifier>jakarta</classifier>
    </dependency>
    <dependency> <!-- TODO: remove after core merge -->
      <groupId>org.primefaces.extensions</groupId>
      <artifactId>primefaces-extensions</artifactId>
      <version>15.0.17</version>
      <classifier>jakarta</classifier>
    </dependency>
    <dependency>
      <groupId>software.xdev</groupId>
      <artifactId>chartjs-java-model</artifactId>
      <version>2.9.1</version> <!-- TODO: remove after core merge -->
    </dependency>
  </dependencies>

  <build>
    <testSourceDirectory>src_test</testSourceDirectory>
    <plugins>
      <plugin>
        <groupId>com.axonivy.ivy.ci</groupId>
        <artifactId>project-build-plugin</artifactId>
      </plugin>

      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <skip>${skip.tests}</skip>
          <testFailureIgnore>true</testFailureIgnore>
          <reuseForks>false</reuseForks>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>cockpit</id>
      <properties>
        <skip.tests>false</skip.tests>
      </properties>
    </profile>
  </profiles>
</project>
