# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/variables.json
Variables:
  # Default Dashboard
  # [file: json]
  PORTAL_DASHBOARD: ""
  # test variable
  variable: hello
  # test boolean
  booleanTest: true
  # test number
  number: 123
  # test password
  #[password]
  password: ${decrypt:IVYB1lRC/+7X7J5Is6mFhA==}
  # test daytime
  # [daytime]
  daytime: '10:30'
  # test enum
  # [enum: hi, hello, hallo]
  enumTest: hi
  # This is a global variable for testing
  globVar: 'data'
