Variables:
  # Default Dashboard
  # [file: json]
  PORTAL_DASHBOARD: 
  # test variable
  variable: hello
  # test boolean
  boolean: true
  # test number
  number: 123
  # test password
  # [password]
  password: test
  # test daytime
  # [daytime]
  daytime: '10:30'
  # test enum
  # [enum: hi, hello, hallo]
  enum: hi