# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/webservice-clients-3.json
WebServiceClients:
  #this is a web service
  test-web:
    Name: test-web
    ServiceClass: ch.ivyteam.testservice.country.client.CountryServiceService
    Features:
      - ch.ivyteam.ivy.webservice.exec.cxf.feature.HttpBasicAuthenticationFeature
    Properties:
      username: admin
      sensitive: ${decrypt:RNQ+L1moXUs2p3WTlXGFcw==}
      password: ${decrypt:LtEQqeGP4ndLIOemOynoXA==}
    Endpoints:
      CountryServicePort:
        - http://test-webservices.ivyteam.io:91/country-service/webservices/country
        - localhost
        - localhost/test
    Codegen:
      WsdlUrl: http://test-webservices.ivyteam.io:8080/country-service/webservices/country?wsdl
      Namespace: ch.ivyteam.testservice.country.client
  #test web service
  second-web:
    Name: second-web
    ServiceClass: com.smartbear.client.SampleWebService
    Codegen:
      WsdlUrl: blabla
