WebServiceClients:
  #this is a web service
  test-web:
    Id: 16AB1778C1FA54E5
    ServiceClass: com.smartbear.client.SampleWebService
    WsdlUrl: http://secure.smartbearsoftware.com/samples/testcomplete12/webservices/Service.asmx?WSDL
    WsCallLibrary: CXF
    Features:
    - ch.ivyteam.ivy.webservice.exec.cxf.feature.HttpBasicAuthenticationFeature
    Properties:
      username: admin
      password: admin
    Endpoints:
      SampleWebServiceSoap:
      - http://secure.smartbearsoftware.com/samples/testcomplete12/webservices/Service.asmx
      - localhost
      - localhost/test
      SampleWebServiceSoap12:
      - http://secure.smartbearsoftware.com/samples/testcomplete12/webservices/Service.asmx
      - test.com
  #test web service
  second-web:
    Id: 17A86479A1CF0D33
    WsdlUrl: blabla
    Endpoints: {}
