WebServiceClients:
  #this is a web service
  test-web:
    Id: 16AB1778C1FA54E5
    ServiceClass: com.smartbear.client.SampleWebService
    WsdlUrl: http://secure.smartbearsoftware.com/samples/testcomplete12/webservices/Service.asmx?WSDL
    WsCallLibrary: CXF
    Features:
    - ch.ivyteam.ivy.webservice.exec.cxf.feature.HttpBasicAuthenticationFeature
    Properties:
      username: admin
      password: ${decrypt:\u0075\u0070\u00A9\u00EF\u009C\u0075\u0055\u0041\u0008\u0098\u005E\u0085\u00B2\u000D\u00E2\u00E3\u0097\u0089\u007D\u0054\u002D\u0058\u006C\u002D\u00B0\u0087\u00ED\u004E\u00ED\u00B0\u005A\u002D}
      sensitive: ${decrypt:\u00CA\u00F6\u0032\u0068\u0022\u003E\u00AF\u0011\u0083\u00B7\u0007\u0053\u0051\u00A2\u00C4\u00F0\u0051\u00B0\u00C0\u003B\u0000\u00CE\u006E\u00AC\u00DC\u00F8\u0074\u0057\u004F\u000B\u00DA\u0066\u0016\u0076\u00C9\u0075\u00C8\u0076\u0094\u0077\u00ED\u0042\u00C9\u0093\u00B4\u0026\u0033\u00B3\u0091\u00D3\u002A\u001B\u0033\u00F8\u00D4\u00C5\u0034\u0049\u003A\u003A\u00A4\u00AA\u00EF\u00DC}
    Endpoints:
      SampleWebServiceSoap:
      - http://secure.smartbearsoftware.com/samples/testcomplete12/webservices/Service.asmx
      - localhost
      - localhost/test
      SampleWebServiceSoap12:
      - http://secure.smartbearsoftware.com/samples/testcomplete12/webservices/Service.asmx
      - test.com
  #test web service
  second-web:
    Id: 17A86479A1CF0D33
    WsdlUrl: blabla
    WsCallLibrary: CXF
    Endpoints: {}
