# == Databases ==
#
# Databases are defined in ivy projects with a name.
#
Databases:
  # This is an example configuration for the database with the name myDb.
  ${name}:
    Url: "${url}"
    Driver: ${driver}
    UserName: ${username}
    Password: "${encrypt:*****}"
    MaxConnections: ${maxConnections}

    # Properties are merged with higher priority with those from the project.
    Properties: ${properties}
